icons_format = "{icon}"

[theme]
theme = "native"

[icons]
icons = "awesome6"

[[block]]
block = "music"
format = "$icon  $combo"

[[block]]
block = "sound"
format = "$icon $volume"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
format = "$icon $percentage"
full_format = "$icon $percentage"
charging_format = "$icon $percentage"
empty_format = "$icon $percentage"
not_charging_format = "$icon $percentage"

[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%d/%m/%y - %R:%S') "
