[env]
TERM = "alacritty"

[font]
size = 8
# transparent_background_colors = false

[font.normal]
family = "scientifica"
#family = "monospace"
#family = "trigon15x8"

[window]
opacity = 1
#dynamic_padding = true

[window.padding]
#x = 0
#y = 0
x = 12
y = 12

[debug]
log_level = "Off"

[keyboard]
bindings = []

[general]
import = ["/home/bean/.cache/wal/alacritty.toml"]
